#!/bin/bash

# Turn off echo
set +x

# Build the iOS
# 需要先安装rust iOS编译工具链: rustup target add aarch64-apple-ios
# 再安装编译工具: cargo install cargo-lipo

# 输出目录在 target/aarch64-apple-ios/release
# aarch64-apple-ios aarch64-apple-ios-sim
#cargo lipo --targets aarch64-apple-ios aarch64-apple-ios-sim --release --package cdylib_demo
cargo lipo --targets aarch64-apple-ios --release --package cdylib_demo
echo "output-> target/aarch64-apple-ios/release"

cargo test --package cdylib_demo --lib generate_headers --features headers
