#!/bin/bash

# Turn off echo
set +x

# 使用默认平台编译 `rustup show active-toolchain`
# stable-x86_64-unknown-linux-gnu (default)
# stable-x86_64-pc-windows-msvc
# 输出目录在 ./release

cargo build --release --package gcode_to_ydd
#cargo build --release --target x86_64-unknown-linux-gnu --package gcode_to_ydd
#cargo build --release --target x86_64-unknown-linux-musl --package gcode_to_ydd

rustup show active-toolchain

open ../target/release