#!/bin/bash

# Turn off echo
set +x

# 使用默认平台编译 `rustup show active-toolchain`
# stable-x86_64-unknown-linux-gnu (default)
# stable-x86_64-pc-windows-msvc
# stable-aarch64-apple-darwin (default)
# 输出目录在 ./release

cargo build --release --package gif_to_ild
#cargo build --release --target x86_64-unknown-linux-gnu --package gif_to_ild
#cargo build --release --target x86_64-unknown-linux-musl --package gif_to_ild

rustup show active-toolchain

open ../target/release